### ISSUE TITLE
Edit Readme to put the following line above "breathing life into code"

### ISSUE THREAD

**Issue by elsowiny** [Black-Axe/.github#27]
### What would you like to share?

Spirans in Codice 

This is the latin translation of breathing life into code and would look nicer on top of the english counterpart

It is a very easy fix involves just placing this line into the readme file\

Located in profile/readme

**Comment by valanm22** [comment]
Shall I work on this?

**Comment by elsowiny** [comment]
@valanm22 yes and thank you!
